import { generateFiles } from 'fumadocs-openapi'
import { openapi } from '../app/lib/openapi.server.ts'

// Regenerates one page per proxy operation from worker/openapi.json. Run after changing the schema.
await generateFiles({
  input: openapi,
  output: './content/docs/reference/proxy-api',
  per: 'operation',
  includeDescription: true,
  addGeneratedComment: 'Generated by `bun run --cwd docs openapi` from worker/openapi.json. Do not edit.',
})
